// Builds the static GitHub Pages site into _site/ (or the directory given as
// the first argument). The pages run without the Node server: the in-browser
// StaticApi (public/js/static-api.js) serves data from data/catalog.json.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = path.resolve(root, process.argv[2] || '_site');

fs.rmSync(out, { recursive: true, force: true });
fs.cpSync(path.join(root, 'public'), out, { recursive: true });
fs.writeFileSync(
  path.join(out, 'js', 'site-config.js'),
  "// Generated by scripts/build-pages.js\nwindow.SITE_CONFIG = { mode: 'static' };\n"
);
// Serve files as-is (no Jekyll processing).
fs.writeFileSync(path.join(out, '.nojekyll'), '');

// Fail the build early if the catalog is malformed.
const catalog = JSON.parse(fs.readFileSync(path.join(out, 'data', 'catalog.json'), 'utf8'));
for (const key of ['settings', 'products', 'templates']) {
  if (!catalog[key]) throw new Error(`data/catalog.json is missing "${key}"`);
}
console.log(`Built static site in ${path.relative(root, out) || '.'} (${catalog.products.length} products, ${catalog.templates.length} templates)`);
