// Default data written to the database on first start.
// All sizes are in millimetres, prices in the configured currency.

const standardColors = [
  { id: 'bw', name: 'Black & White', multiplier: 1 },
  { id: 'cmyk', name: 'Full Color (CMYK)', multiplier: 1.6 },
  { id: 'cmyk-spot', name: 'Full Color + Spot / Pantone', multiplier: 2 },
];

const settings = {
  companyName: 'ColarPrint',
  tagline: 'Print anything, any size — priced instantly.',
  currency: 'USD',
  taxRate: 0,
  contactEmail: 'hello@colarprint.example',
  contactPhone: '+1 555 0100',
  turnarounds: [
    { id: 'standard', name: 'Standard', days: 5, multiplier: 1 },
    { id: 'express', name: 'Express', days: 2, multiplier: 1.3 },
    { id: 'same-day', name: 'Same day', days: 0, multiplier: 1.75 },
  ],
};

const products = [
  {
    id: 'business-cards',
    name: 'Business Cards',
    icon: '💼',
    description: 'Premium business cards on thick card stock. Make a great first impression.',
    active: true,
    pricePerSqm: 60,
    minUnitPrice: 0.05,
    setupFee: 5,
    minQuantity: 50,
    minWidth: 50, maxWidth: 100, minHeight: 50, maxHeight: 100,
    allowCustomSize: true,
    sizePresets: [
      { id: 'us', name: 'US Standard (89 × 51 mm)', width: 89, height: 51 },
      { id: 'eu', name: 'EU Standard (85 × 55 mm)', width: 85, height: 55 },
      { id: 'square', name: 'Square (65 × 65 mm)', width: 65, height: 65 },
    ],
    colorOptions: standardColors,
    materials: [
      { id: 'matte-350', name: 'Matte 350gsm', pricePerSqm: 0 },
      { id: 'gloss-350', name: 'Gloss 350gsm', pricePerSqm: 5 },
      { id: 'kraft', name: 'Recycled Kraft', pricePerSqm: 12 },
      { id: 'linen', name: 'Linen Textured 400gsm', pricePerSqm: 20 },
    ],
    sides: [
      { id: 'single', name: 'Single sided', multiplier: 1 },
      { id: 'double', name: 'Double sided', multiplier: 1.7 },
    ],
    finishes: [
      { id: 'rounded', name: 'Rounded corners', perUnit: 0.02, perSqm: 0, flat: 0 },
      { id: 'soft-touch', name: 'Soft-touch lamination', perUnit: 0, perSqm: 25, flat: 0 },
      { id: 'foil', name: 'Gold foil accent', perUnit: 0.08, perSqm: 0, flat: 25 },
    ],
    quantityTiers: [
      { minQty: 250, discountPct: 10 },
      { minQty: 500, discountPct: 18 },
      { minQty: 1000, discountPct: 25 },
    ],
  },
  {
    id: 'flyers',
    name: 'Flyers & Leaflets',
    icon: '📄',
    description: 'Eye-catching flyers for events, promotions and menus.',
    active: true,
    pricePerSqm: 14,
    minUnitPrice: 0.08,
    setupFee: 5,
    minQuantity: 25,
    minWidth: 90, maxWidth: 450, minHeight: 90, maxHeight: 450,
    allowCustomSize: true,
    sizePresets: [
      { id: 'a6', name: 'A6 (105 × 148 mm)', width: 105, height: 148 },
      { id: 'a5', name: 'A5 (148 × 210 mm)', width: 148, height: 210 },
      { id: 'a4', name: 'A4 (210 × 297 mm)', width: 210, height: 297 },
      { id: 'letter', name: 'US Letter (216 × 279 mm)', width: 216, height: 279 },
      { id: 'dl', name: 'DL (99 × 210 mm)', width: 99, height: 210 },
    ],
    colorOptions: standardColors,
    materials: [
      { id: 'silk-130', name: 'Silk 130gsm', pricePerSqm: 0 },
      { id: 'gloss-170', name: 'Gloss 170gsm', pricePerSqm: 2 },
      { id: 'matte-250', name: 'Matte 250gsm', pricePerSqm: 4 },
    ],
    sides: [
      { id: 'single', name: 'Single sided', multiplier: 1 },
      { id: 'double', name: 'Double sided', multiplier: 1.6 },
    ],
    finishes: [
      { id: 'fold', name: 'Folding', perUnit: 0.03, perSqm: 0, flat: 0 },
      { id: 'gloss-lam', name: 'Gloss lamination', perUnit: 0, perSqm: 6, flat: 0 },
    ],
    quantityTiers: [
      { minQty: 100, discountPct: 8 },
      { minQty: 500, discountPct: 15 },
      { minQty: 1000, discountPct: 22 },
      { minQty: 5000, discountPct: 30 },
    ],
  },
  {
    id: 'posters',
    name: 'Posters',
    icon: '🖼️',
    description: 'Vivid large-format posters in any size — from A3 up to 1.2 metres wide.',
    active: true,
    pricePerSqm: 22,
    minUnitPrice: 3,
    setupFee: 0,
    minQuantity: 1,
    minWidth: 200, maxWidth: 1200, minHeight: 200, maxHeight: 2000,
    allowCustomSize: true,
    sizePresets: [
      { id: 'a3', name: 'A3 (297 × 420 mm)', width: 297, height: 420 },
      { id: 'a2', name: 'A2 (420 × 594 mm)', width: 420, height: 594 },
      { id: 'a1', name: 'A1 (594 × 841 mm)', width: 594, height: 841 },
      { id: 'a0', name: 'A0 (841 × 1189 mm)', width: 841, height: 1189 },
      { id: '18x24', name: '18 × 24 in (457 × 610 mm)', width: 457, height: 610 },
    ],
    colorOptions: standardColors,
    materials: [
      { id: 'satin-200', name: 'Satin Photo 200gsm', pricePerSqm: 0 },
      { id: 'gloss-photo', name: 'High-gloss Photo 260gsm', pricePerSqm: 8 },
      { id: 'backlit', name: 'Backlit Film', pricePerSqm: 18 },
    ],
    sides: [{ id: 'single', name: 'Single sided', multiplier: 1 }],
    finishes: [
      { id: 'lamination', name: 'Matte lamination', perUnit: 0, perSqm: 9, flat: 0 },
      { id: 'foam-board', name: 'Mount on 5mm foam board', perUnit: 2, perSqm: 25, flat: 0 },
    ],
    quantityTiers: [
      { minQty: 5, discountPct: 5 },
      { minQty: 20, discountPct: 12 },
      { minQty: 50, discountPct: 20 },
    ],
  },
  {
    id: 'banners',
    name: 'Vinyl Banners',
    icon: '🎌',
    description: 'Durable outdoor vinyl banners with hems and grommets. Up to 5 metres long.',
    active: true,
    pricePerSqm: 18,
    minUnitPrice: 15,
    setupFee: 10,
    minQuantity: 1,
    minWidth: 300, maxWidth: 5000, minHeight: 300, maxHeight: 2500,
    allowCustomSize: true,
    sizePresets: [
      { id: '2x4ft', name: '4 × 2 ft (1219 × 610 mm)', width: 1219, height: 610 },
      { id: '3x6ft', name: '6 × 3 ft (1829 × 914 mm)', width: 1829, height: 914 },
      { id: '1x3m', name: '3 × 1 m', width: 3000, height: 1000 },
      { id: '2x5m', name: '5 × 2 m', width: 5000, height: 2000 },
    ],
    colorOptions: standardColors,
    materials: [
      { id: 'vinyl-440', name: 'Vinyl 440gsm', pricePerSqm: 0 },
      { id: 'mesh', name: 'Wind-through Mesh', pricePerSqm: 4 },
      { id: 'blockout', name: 'Blockout (double sided)', pricePerSqm: 9 },
    ],
    sides: [
      { id: 'single', name: 'Single sided', multiplier: 1 },
      { id: 'double', name: 'Double sided (blockout only)', multiplier: 1.8 },
    ],
    finishes: [
      { id: 'grommets', name: 'Hems & grommets', perUnit: 4, perSqm: 0, flat: 0 },
      { id: 'pole-pockets', name: 'Pole pockets', perUnit: 8, perSqm: 0, flat: 0 },
    ],
    quantityTiers: [
      { minQty: 3, discountPct: 5 },
      { minQty: 10, discountPct: 12 },
    ],
  },
  {
    id: 'stickers',
    name: 'Stickers & Labels',
    icon: '🏷️',
    description: 'Custom die-cut stickers and product labels, waterproof and UV resistant.',
    active: true,
    pricePerSqm: 45,
    minUnitPrice: 0.12,
    setupFee: 8,
    minQuantity: 25,
    minWidth: 20, maxWidth: 300, minHeight: 20, maxHeight: 300,
    allowCustomSize: true,
    sizePresets: [
      { id: '50', name: '50 × 50 mm', width: 50, height: 50 },
      { id: '75', name: '75 × 75 mm', width: 75, height: 75 },
      { id: '100x50', name: '100 × 50 mm label', width: 100, height: 50 },
    ],
    colorOptions: standardColors,
    materials: [
      { id: 'white-vinyl', name: 'White Vinyl', pricePerSqm: 0 },
      { id: 'clear-vinyl', name: 'Clear Vinyl', pricePerSqm: 8 },
      { id: 'holographic', name: 'Holographic', pricePerSqm: 30 },
    ],
    sides: [{ id: 'single', name: 'Single sided', multiplier: 1 }],
    finishes: [
      { id: 'die-cut', name: 'Custom die-cut shape', perUnit: 0.04, perSqm: 0, flat: 15 },
      { id: 'laminate', name: 'UV laminate', perUnit: 0, perSqm: 12, flat: 0 },
    ],
    quantityTiers: [
      { minQty: 100, discountPct: 10 },
      { minQty: 500, discountPct: 20 },
      { minQty: 2000, discountPct: 30 },
    ],
  },
  {
    id: 'canvas',
    name: 'Canvas Prints',
    icon: '🎨',
    description: 'Gallery-wrapped canvas prints on a solid pine frame, ready to hang.',
    active: true,
    pricePerSqm: 55,
    minUnitPrice: 19,
    setupFee: 0,
    minQuantity: 1,
    minWidth: 200, maxWidth: 1500, minHeight: 200, maxHeight: 1500,
    allowCustomSize: true,
    sizePresets: [
      { id: '30x40', name: '30 × 40 cm', width: 300, height: 400 },
      { id: '50x50', name: '50 × 50 cm', width: 500, height: 500 },
      { id: '60x90', name: '60 × 90 cm', width: 900, height: 600 },
    ],
    colorOptions: standardColors,
    materials: [
      { id: 'cotton', name: 'Cotton Canvas', pricePerSqm: 0 },
      { id: 'poly-cotton', name: 'Premium Poly-Cotton', pricePerSqm: 10 },
    ],
    sides: [{ id: 'single', name: 'Front only', multiplier: 1 }],
    finishes: [
      { id: 'thick-frame', name: '38mm thick frame', perUnit: 6, perSqm: 0, flat: 0 },
      { id: 'varnish', name: 'Protective varnish', perUnit: 0, perSqm: 12, flat: 0 },
    ],
    quantityTiers: [{ minQty: 3, discountPct: 8 }],
  },
];

// Template elements use percentage coordinates (0-100) relative to the print
// area so a template adapts to whatever size the customer picks.
// Text `size` is a percentage of the print height.
const templates = [
  {
    id: 'bc-modern',
    name: 'Modern Minimal',
    category: 'Business',
    productIds: ['business-cards'],
    width: 89, height: 51,
    background: '#ffffff',
    tags: ['minimal', 'clean', 'corporate'],
    elements: [
      { id: 'bar', type: 'rect', x: 0, y: 0, w: 6, h: 100, fill: '#2563eb' },
      { id: 'name', type: 'text', label: 'Full name', text: 'Alex Morgan', x: 14, y: 34, size: 14, color: '#111827', weight: 'bold', align: 'start', editable: true },
      { id: 'title', type: 'text', label: 'Job title', text: 'Creative Director', x: 14, y: 48, size: 8, color: '#2563eb', weight: 'normal', align: 'start', editable: true },
      { id: 'contact', type: 'text', label: 'Contact', text: 'alex@company.com\n+1 555 0100', x: 14, y: 72, size: 7, color: '#4b5563', weight: 'normal', align: 'start', editable: true },
    ],
  },
  {
    id: 'bc-bold',
    name: 'Bold Dark',
    category: 'Business',
    productIds: ['business-cards'],
    width: 85, height: 55,
    background: '#111827',
    tags: ['dark', 'bold'],
    elements: [
      { id: 'circle', type: 'circle', cx: 88, cy: 18, r: 30, fill: '#f59e0b' },
      { id: 'company', type: 'text', label: 'Company', text: 'NORTHWIND', x: 8, y: 30, size: 13, color: '#f59e0b', weight: 'bold', align: 'start', editable: true },
      { id: 'name', type: 'text', label: 'Full name', text: 'Jordan Lee', x: 8, y: 62, size: 10, color: '#ffffff', weight: 'bold', align: 'start', editable: true },
      { id: 'contact', type: 'text', label: 'Contact', text: 'jordan@northwind.co · 555 0199', x: 8, y: 80, size: 6, color: '#d1d5db', weight: 'normal', align: 'start', editable: true },
    ],
  },
  {
    id: 'bc-classic',
    name: 'Classic Centered',
    category: 'Business',
    productIds: ['business-cards'],
    width: 89, height: 51,
    background: '#fdf6e3',
    tags: ['classic', 'elegant'],
    elements: [
      { id: 'line', type: 'rect', x: 35, y: 55, w: 30, h: 1.2, fill: '#92400e' },
      { id: 'name', type: 'text', label: 'Full name', text: 'Sam Rivera', x: 50, y: 42, size: 14, color: '#78350f', weight: 'bold', align: 'middle', editable: true },
      { id: 'title', type: 'text', label: 'Job title', text: 'Attorney at Law', x: 50, y: 70, size: 7, color: '#92400e', weight: 'normal', align: 'middle', editable: true },
      { id: 'contact', type: 'text', label: 'Contact', text: 'sam@rivera-law.com', x: 50, y: 84, size: 6, color: '#78350f', weight: 'normal', align: 'middle', editable: true },
    ],
  },
  {
    id: 'flyer-event',
    name: 'Event Night',
    category: 'Events',
    productIds: ['flyers', 'posters'],
    width: 148, height: 210,
    background: '#1e1b4b',
    tags: ['party', 'event', 'music'],
    elements: [
      { id: 'glow', type: 'circle', cx: 50, cy: 30, r: 38, fill: '#7c3aed' },
      { id: 'headline', type: 'text', label: 'Headline', text: 'SUMMER\nNIGHTS', x: 50, y: 26, size: 9, color: '#ffffff', weight: 'bold', align: 'middle', editable: true },
      { id: 'date', type: 'text', label: 'Date', text: 'SAT · JULY 18 · 9PM', x: 50, y: 66, size: 3.6, color: '#fbbf24', weight: 'bold', align: 'middle', editable: true },
      { id: 'venue', type: 'text', label: 'Venue', text: 'The Warehouse, 12 Dock Street', x: 50, y: 74, size: 2.6, color: '#e0e7ff', weight: 'normal', align: 'middle', editable: true },
      { id: 'cta', type: 'rect', x: 25, y: 83, w: 50, h: 7, fill: '#fbbf24', rx: 2 },
      { id: 'cta-text', type: 'text', label: 'Button text', text: 'GET TICKETS', x: 50, y: 87.8, size: 2.8, color: '#1e1b4b', weight: 'bold', align: 'middle', editable: true },
    ],
  },
  {
    id: 'flyer-sale',
    name: 'Big Sale',
    category: 'Retail',
    productIds: ['flyers', 'posters', 'banners'],
    width: 210, height: 297,
    background: '#fef2f2',
    tags: ['sale', 'discount', 'retail'],
    elements: [
      { id: 'top', type: 'rect', x: 0, y: 0, w: 100, h: 38, fill: '#dc2626' },
      { id: 'headline', type: 'text', label: 'Headline', text: 'MEGA SALE', x: 50, y: 20, size: 9, color: '#ffffff', weight: 'bold', align: 'middle', editable: true },
      { id: 'sub', type: 'text', label: 'Subheading', text: 'Up to', x: 50, y: 30, size: 3.5, color: '#fee2e2', weight: 'normal', align: 'middle', editable: true },
      { id: 'pct', type: 'text', label: 'Discount', text: '50% OFF', x: 50, y: 58, size: 14, color: '#dc2626', weight: 'bold', align: 'middle', editable: true },
      { id: 'details', type: 'text', label: 'Details', text: 'Everything in store · This weekend only', x: 50, y: 72, size: 2.8, color: '#7f1d1d', weight: 'normal', align: 'middle', editable: true },
      { id: 'store', type: 'text', label: 'Store name', text: 'YOUR STORE NAME', x: 50, y: 90, size: 3.5, color: '#111827', weight: 'bold', align: 'middle', editable: true },
    ],
  },
  {
    id: 'poster-minimal',
    name: 'Swiss Minimal',
    category: 'Art',
    productIds: ['posters', 'canvas'],
    width: 297, height: 420,
    background: '#f5f5f4',
    tags: ['art', 'minimal', 'typography'],
    elements: [
      { id: 'block', type: 'rect', x: 10, y: 10, w: 55, h: 55, fill: '#ea580c' },
      { id: 'dot', type: 'circle', cx: 72, cy: 60, r: 14, fill: '#0f172a' },
      { id: 'title', type: 'text', label: 'Title', text: 'FORM\nFOLLOWS\nFUNCTION', x: 10, y: 76, size: 5, color: '#0f172a', weight: 'bold', align: 'start', editable: true },
      { id: 'caption', type: 'text', label: 'Caption', text: 'Exhibition · 2026', x: 10, y: 95, size: 1.8, color: '#57534e', weight: 'normal', align: 'start', editable: true },
    ],
  },
  {
    id: 'banner-opening',
    name: 'Grand Opening',
    category: 'Retail',
    productIds: ['banners'],
    width: 1829, height: 914,
    background: '#065f46',
    tags: ['opening', 'store', 'outdoor'],
    elements: [
      { id: 'stripe', type: 'rect', x: 0, y: 78, w: 100, h: 22, fill: '#fbbf24' },
      { id: 'headline', type: 'text', label: 'Headline', text: 'GRAND OPENING', x: 50, y: 40, size: 22, color: '#ffffff', weight: 'bold', align: 'middle', editable: true },
      { id: 'sub', type: 'text', label: 'Subheading', text: 'Join us this Saturday — free coffee for everyone!', x: 50, y: 60, size: 7, color: '#d1fae5', weight: 'normal', align: 'middle', editable: true },
      { id: 'web', type: 'text', label: 'Website', text: 'www.yourbusiness.com', x: 50, y: 92, size: 8, color: '#065f46', weight: 'bold', align: 'middle', editable: true },
    ],
  },
  {
    id: 'banner-birthday',
    name: 'Happy Birthday',
    category: 'Events',
    productIds: ['banners', 'posters'],
    width: 3000, height: 1000,
    background: '#fdf2f8',
    tags: ['birthday', 'party', 'celebration'],
    elements: [
      { id: 'b1', type: 'circle', cx: 8, cy: 30, r: 18, fill: '#f472b6' },
      { id: 'b2', type: 'circle', cx: 92, cy: 30, r: 18, fill: '#60a5fa' },
      { id: 'b3', type: 'circle', cx: 16, cy: 75, r: 12, fill: '#facc15' },
      { id: 'b4', type: 'circle', cx: 84, cy: 75, r: 12, fill: '#34d399' },
      { id: 'headline', type: 'text', label: 'Headline', text: 'HAPPY BIRTHDAY', x: 50, y: 50, size: 26, color: '#be185d', weight: 'bold', align: 'middle', editable: true },
      { id: 'name', type: 'text', label: 'Name', text: 'EMMA!', x: 50, y: 82, size: 16, color: '#1e3a8a', weight: 'bold', align: 'middle', editable: true },
    ],
  },
  {
    id: 'sticker-round',
    name: 'Round Badge',
    category: 'Branding',
    productIds: ['stickers'],
    width: 75, height: 75,
    background: '#ffffff',
    tags: ['logo', 'badge', 'round'],
    elements: [
      { id: 'ring', type: 'circle', cx: 50, cy: 50, r: 48, fill: '#0f766e' },
      { id: 'inner', type: 'circle', cx: 50, cy: 50, r: 40, fill: '#ffffff' },
      { id: 'brand', type: 'text', label: 'Brand', text: 'BREW CO.', x: 50, y: 50, size: 13, color: '#0f766e', weight: 'bold', align: 'middle', editable: true },
      { id: 'since', type: 'text', label: 'Tagline', text: 'SINCE 2020', x: 50, y: 66, size: 6, color: '#115e59', weight: 'normal', align: 'middle', editable: true },
    ],
  },
  {
    id: 'label-product',
    name: 'Product Label',
    category: 'Branding',
    productIds: ['stickers'],
    width: 100, height: 50,
    background: '#fffbeb',
    tags: ['label', 'jar', 'product'],
    elements: [
      { id: 'border', type: 'rect', x: 4, y: 8, w: 92, h: 84, fill: '#b45309', rx: 3 },
      { id: 'inner', type: 'rect', x: 6, y: 12, w: 88, h: 76, fill: '#fffbeb', rx: 2 },
      { id: 'product', type: 'text', label: 'Product name', text: 'Wild Honey', x: 50, y: 48, size: 18, color: '#78350f', weight: 'bold', align: 'middle', editable: true },
      { id: 'detail', type: 'text', label: 'Details', text: '100% raw · 250g', x: 50, y: 72, size: 8, color: '#92400e', weight: 'normal', align: 'middle', editable: true },
    ],
  },
  {
    id: 'canvas-quote',
    name: 'Inspirational Quote',
    category: 'Art',
    productIds: ['canvas', 'posters'],
    width: 500, height: 500,
    background: '#0f172a',
    tags: ['quote', 'home', 'decor'],
    elements: [
      { id: 'mark', type: 'text', label: 'Quote mark', text: '“', x: 50, y: 30, size: 22, color: '#38bdf8', weight: 'bold', align: 'middle', editable: false },
      { id: 'quote', type: 'text', label: 'Quote', text: 'Dream big.\nStart small.\nAct now.', x: 50, y: 48, size: 7, color: '#f8fafc', weight: 'bold', align: 'middle', editable: true },
      { id: 'author', type: 'text', label: 'Author', text: '— Robin Sharma', x: 50, y: 82, size: 3.5, color: '#94a3b8', weight: 'normal', align: 'middle', editable: true },
    ],
  },
];

function createSeed() {
  // Deep clone so callers can mutate freely.
  return JSON.parse(JSON.stringify({ settings, products, templates, orders: [] }));
}

module.exports = { createSeed };
